---
- name: Set zabbix_server_major_version
  ansible.builtin.set_fact:
    zabbix_server_major_version: "{{ zabbix_server_version | regex_replace('^([0-9]+\\.[0-9]+)(.*)$', '\\1') }}"
- name: Set zabbix_server_package
  ansible.builtin.set_fact:
    zabbix_server_package: 1:{{ zabbix_server_version }}+{{ ansible_distribution | lower + ansible_distribution_major_version }}
- name: Set zabbix_frontend_php_package
  ansible.builtin.set_fact:
    zabbix_frontend_php_package: 1:{{ zabbix_server_version }}+{{ ansible_distribution | lower + ansible_distribution_major_version }}

- name: Remove deprecated files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/local-repo.zabbix.com-zabbix.list.disabled
    - /usr/share/keyrings/zabbix-official-repo.gpg

- name: Hold zabbix-agent package
  ansible.builtin.dpkg_selections:
    name: zabbix-agent
    selection: hold
  changed_when: false

## Install package ============================================================

- name: Set defaults
  ansible.builtin.set_fact:
    apt_keyrings: /etc/apt/keyrings
    # used for filenames
    visible_name: zabbix-official-repo
- name: Set defaults
  ansible.builtin.set_fact:
    local_apt_key: "{{ apt_keyrings }}/{{ visible_name }}.gpg"
- name: Set defaults
  ansible.builtin.set_fact:
    apt_package: zabbix-server-mysql={{ zabbix_server_package }},zabbix-frontend-php={{ zabbix_frontend_php_package }}
    apt_source_list_name: local-{{ visible_name }}.list
    apt_repository:
      deb [signed-by={{ local_apt_key }}] https://repo.zabbix.com/zabbix/{{ zabbix_server_major_version }}/stable/debian {{ ansible_distribution_release }}
      main
    gpg_key_src: https://repo.zabbix.com/zabbix-official-repo.key

- name: Install zabbix
  ansible.builtin.include_tasks: install.yml

## Configure ==================================================================

- name: Unhold zabbix-agent package
  ansible.builtin.dpkg_selections:
    name: zabbix-agent
    selection: install
  changed_when: false

- name: Copy php-fpm configuration
  ansible.builtin.copy:
    src: php-fpm-zabbix.conf
    dest: /etc/php/8.2/fpm/pool.d/zabbix.conf
    mode: "644"

- name: Copy nginx configuration
  ansible.builtin.copy:
    src: local-mit-zabbix-frontend-{{ zabbix_server_major_version }}.include
    dest: /etc/nginx/conf.d/local-mit-zabbix-frontend.include
    mode: "644"

- name: Set permissions on /etc/zabbix/web/zabbix.conf.php
  ansible.builtin.file:
    path: /etc/zabbix/web/zabbix.conf.php
    owner: root
    group: www-data
    mode: "640"

# #21395: Ensure Zabbix is stopped and started with database
- name: Create /etc/systemd/system/zabbix-server.service.d
  ansible.builtin.file:
    path: /etc/systemd/system/zabbix-server.service.d
    state: directory
    mode: "755"
- name: Add systemd dependency to mariadb.service
  ansible.builtin.copy:
    src: etc/systemd/system/zabbix-server.service.d/override.conf
    dest: /etc/systemd/system/zabbix-server.service.d/override.conf
    mode: "644"
  notify:
    - Reload systemd
    # Create symlink /etc/systemd/system/mariadb.service.wants/zabbix-server.service → /lib/systemd/system/zabbix-server.service.
    - Update zabbix-server.service WantedBy
