---

- set_fact:
    zabbix_server_major_version: "{{ zabbix_server_version | regex_replace('^([0-9]+\\.[0-9]+)(.*)$', '\\1') }}"
- set_fact:
    zabbix_server_package: "1:{{ zabbix_server_version }}+{{ ansible_distribution|lower + ansible_distribution_major_version }}"
- set_fact:
    zabbix_frontend_php_package: "1:{{ zabbix_server_version }}+{{ ansible_distribution|lower + ansible_distribution_major_version }}"
- set_fact:
    apt_repository_zabbix: "deb [signed-by=/usr/share/keyrings/zabbix-official-repo.gpg] https://repo.zabbix.com/zabbix/{{ zabbix_server_major_version }}/debian {{ ansible_distribution_release }} main"

- name: "Add apt gpg key for repo.zabbix.com"
  copy: src=zabbix-official-repo.gpg dest=/usr/share/keyrings/

- name: "Enable apt repository (changed_when: no)"
  apt_repository:
    repo: "{{ apt_repository_zabbix }}"
    state: present
  changed_when: no
- name: "Update zabbix-server-mysql and zabbix-frontend-php to {{ zabbix_server_version }}"
  apt: 
    name: zabbix-server-mysql={{ zabbix_server_package }},zabbix-frontend-php={{ zabbix_frontend_php_package }}
    update_cache: yes
- name: "Deactivate apt repository (changed_when: no)"
  apt_repository:
    repo: "{{ apt_repository_zabbix }}"
    state: absent
  changed_when: no
- name: Remove local-repo_zabbix_com_zabbix.list
  file:
    path: /etc/apt/sources.list.d/local-repo.zabbix.com-zabbix.list
    state: absent
- name: Add (disabled) local-repo_zabbix_com_zabbix.list
  template:
    src: local-repo.zabbix.com-zabbix.list
    dest: /etc/apt/sources.list.d/local-repo.zabbix.com-zabbix.list.disabled

- name: Copy php-fpm configuration
  copy:
    src: php-fpm-zabbix.conf
    dest: /etc/php/7.4/fpm/pool.d/zabbix.conf
- name: Copy nginx configuration
  copy: 
    src: local-mit-zabbix-frontend-{{ zabbix_server_major_version }}.include
    dest: /etc/nginx/conf.d/local-mit-zabbix-frontend.include

#21395: Ensure Zabbix is stopped and started with database
- name: Create /etc/systemd/system/zabbix-server.service.d
  file:
    path: /etc/systemd/system/zabbix-server.service.d
    state: directory
- name: Add systemd dependency to mariadb.service
  copy:
    src: etc/systemd/system/zabbix-server.service.d/override.conf
    dest: /etc/systemd/system/zabbix-server.service.d/override.conf
  notify:
    - Reload systemd
    # Create symlink /etc/systemd/system/mariadb.service.wants/zabbix-server.service → /lib/systemd/system/zabbix-server.service.
    - Update zabbix-server.service WantedBy

