---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Update zabbix-server.service WantedBy
  # ansible.builtin.systemd will not execute if serivce is already enabled
  ansible.builtin.command: systemctl enable zabbix-server.service
